INSERT INTO Authors VALUE ("George Orwell", "A01");
INSERT INTO Authors VALUE ("Gabriel Garcia Marquez","A02");
INSERT INTO Authors VALUE ("Aldous Huxley", "A03");
INSERT INTO Authors VALUE ("Fyodor Dostoevsky", "A04");
INSERT INTO Authors VALUE ("C.S. Lewis", "A05");
INSERT INTO Authors VALUE ("Mary Shelley", "A06");
INSERT INTO Authors VALUE ("John Steinbeck", "A07");
INSERT INTO Authors VALUE ("Mark Twain", "A08");
INSERT INTO Authors VALUE ("Charles Dickens", "A09");
INSERT INTO Authors VALUE ("Joseph Heller", "A10");
INSERT INTO Authors VALUE ("Homer", "A11");
INSERT INTO Authors VALUE ("Victor Hugo", "A12");
INSERT INTO Authors VALUE ("James Joyce", "A13");
INSERT INTO Authors VALUE ("Vladimir Nabokov", "A14");
INSERT INTO Authors VALUE ("Ayn Rand", "A15");
INSERT INTO Authors VALUE ("Patrick Suskind", "A16");
INSERT INTO Authors VALUE ("Franz Kafka", "A17");
INSERT INTO Authors VALUE ("Bret Easton Ellis", "A18");
INSERT INTO Authors VALUE ("Rene Goscinny", "A19");
INSERT INTO Authors VALUE ("Albert Uderzo", "A19");
INSERT INTO Authors VALUE ("Ray Bradbury", "A20");
INSERT INTO Authors VALUE ("Isaac Asimov", "A21");
INSERT INTO Authors VALUE ("Karl Marx", "A22");
INSERT INTO Authors VALUE ("Friedrich Engels", "A22");
INSERT INTO Authors VALUE ("Thomas Paine", "A23");
INSERT INTO Authors VALUE ("Niccolo Machiavelli", "A24");
INSERT INTO Authors VALUE ("Adam Smith", "A25");
INSERT INTO Authors VALUE ("Miguel de Cervantes Saavedra", "A26");
INSERT INTO Authors VALUE ("Simone de Beauvoir", "A27");
INSERT INTO Authors VALUE ("Immanuel Kant", "A28");
INSERT INTO Authors VALUE ("Charles Darwin", "A29");
INSERT INTO Authors VALUE ("Isaac Newton", "A30");
INSERT INTO Authors VALUE ("Milan Kundera", "A31");
INSERT INTO Authors VALUE ("Sun Tzu", "A32");
INSERT INTO Authors VALUE ("Jorge Luis Borges", "A33");
INSERT INTO Authors VALUE ("Gabriel Garcia Marquez", "A34");
INSERT INTO Authors VALUE ("Juan Rulfo", "A35");
INSERT INTO Authors VALUE ("Octavio Paz", "A36");
INSERT INTO Authors VALUE ("Pablo Neruda", "A37");
INSERT INTO Authors VALUE ("Richard Feynman", "A38");
INSERT INTO Authors VALUE ("Stephen Hawking", "A39");
INSERT INTO Authors VALUE ("Carl Sagan", "A40");
INSERT INTO Authors VALUE ("Silvanus P. Thompso", "A41");
INSERT INTO Authors VALUE ("Martin Gardner", "A41");
INSERT INTO Authors VALUE ("Enrico Fermi", "A42");
INSERT INTO Authors VALUE ("Alexander Hamilton", "A43");
INSERT INTO Authors VALUE ("James Madison", "A43");
INSERT INTO Authors VALUE ("John Jay", "A43");
INSERT INTO Authors VALUE ("John Lcke", "A44");
INSERT INTO Authors VALUE ("C. B. Macpherson", "A44");
INSERT INTO Authors VALUE ("Karl Popper", "A45");
INSERT INTO Authors VALUE ("Howard Zinn", "A46");
INSERT INTO Authors VALUE ("William Golding", "A47");
INSERT INTO Authors VALUE ("George Orwell", "A48");
INSERT INTO Authors VALUE ("Ernest Hemingway", "A49");
INSERT INTO Authors VALUE ("Luo Guanzhong", "A50");